name: wirepay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans_10pt-Black.ttf
          weight: 900
        - asset: fonts/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: fonts/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: fonts/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: fonts/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: fonts/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: fonts/NunitoSans_10pt-ExtraLight.ttf
          weight: 200

    - family: BricolageGrotesque
      fonts:
        - asset: fonts/BricolageGrotesque-ExtraBold.ttf
          weight: 700
        - asset: fonts/BricolageGrotesque-Bold.ttf
          weight: 700
        - asset: fonts/BricolageGrotesque-SemiBold.ttf
          weight: 600
        - asset: fonts/BricolageGrotesque-Medium.ttf
          weight: 500
        - asset: fonts/BricolageGrotesque-Regular.ttf
          weight: 400
        - asset: fonts/BricolageGrotesque-Light.ttf
          weight: 300
        - asset: fonts/BricolageGrotesque-ExtraLight.ttf
          weight: 200
    - family: AvenirLTStd
      fonts:
        - asset: fonts/AvenirLTStd-Black.otf
          weight: 900
        - asset: fonts/AvenirLTStd-Heavy.otf
          weight: 800
        - asset: fonts/AvenirLTStd-Medium.otf
          weight: 500
        - asset: fonts/AvenirLTStd-Roman.otf
          weight: 400
        - asset: fonts/AvenirLTStd-Book.otf
          weight: 300
        - asset: fonts/AvenirLTStd-Light.otf
          weight: 200
